language: swift
osx_image: xcode11.1
  
xcode_destination: platform=iOS Simulator,OS=11.3,name=iPhone X

env:
    bundle_id: com.cuilingshi.fileextract
    callback_url: http://api-mas-admin-test.yodo1.com/api/mas/task/async/3258d827-e7bc-4cf4-98f2-f84e4b3f0ffe
    sdk_key: rNHXebCtrUWyeDeAihKoDCmwM9sL2WfshXTVHs-7N0yUBE4D0KtcycoTQgE7Ha2a9CsCn9WI22ZwsJQ29h6LzI
    app_name: Unzip - zip file opener
    
cache:
  bundler: true
  directories:
    - Carthage

script: "sh applovin_auto_initialization.sh $bundle_id $callback_url $sdk_key $app_name"
